name: pr
concurrency:
  group: ${{github.head_ref}}
  cancel-in-progress: true
on:
  - pull_request
  - workflow_dispatch
jobs:
  debug:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup
      - run: pnpm build
      - name: Setup tmate session for SSH debugging
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          timeout-minutes: 30
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup
      - run: pnpm add dprint
      - run: pnpm check:format
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm tsx repro-kit-width.ts
      - run: FORCE_COLOR=3 pnpm vitest --run --no-coverage
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm check:lint
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm check:types
