name: pr
concurrency:
  group: ${{github.head_ref}}
  cancel-in-progress: true
on:
  - pull_request
jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: pnpm add dprint
      - run: pnpm check:format
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: FORCE_COLOR=3 pnpm vitest --run --no-coverage
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm check:lint
  types:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm check:types
